### PR TITLE
[Bugfix] Script compilation errors (v4.04a)

### PR DESCRIPTION
**Pull request by Drakehinst**
Added missing lines from v4.04a scripts including support for Intel XESS, HDR, widescreen and various other functionalities.

### CODE REVIEW

**Comment by stiffsen** [comment]
Hi @Drakehinst, thank you for this PR. I don't play W3 anymore and because it is such a hassle to update the mod with each new version of the game, I eventually stopped doing it. As you seem to be interested in doing that work, I would like to offer you access the nexus mods page, so you can upload updates etc. If you agree, please send me your details, and I will make it happen.

**Comment by Drakehinst** [comment]
Hi! Thanks for the feedback, unfortunately I was only making a short test on TW3 and fell into the rabbit hole when wanting to mod the player movements as I found that BetterMovement was no longer maintained. Probably a one-time only contribution on my end I'm afraid.

However I'm open for your suggestion to upload this one patch to Nexus, so here's my profile if that's what you'd need: [https://www.nexusmods.com/users/5529601](https://www.nexusmods.com/users/5529601).

**Comment by stiffsen** [comment]
Great @Drakehinst. You do know how to release the mod as a package for TW3MM, right?

**Comment by Drakehinst** [comment]
Yes, I guess. Is there anything specific to do beyond putting the bin/, content/, localization/ folders and the readme in a folder "modBetterMovement" then zipping it?

**Comment by stiffsen** [comment]
That should be about it. I authorized you. You can push the update to the page and if people say it works, I will accept this PR, as I don't have a way to properly review it.

**Comment by Drakehinst** [comment]
Thanks, I just uploaded the update! Do you think there is any need to notify the users, or would they typically find out about the update through TW3MM if they are not looking regularly on Nexus?

**Comment by stiffsen** [comment]
I don't think there is any way to notify users. It will show in the updated mods list on nexus mods and users get notification if they activated notifications for a mod.

Apparently, there is already a bug report in the comments. Not sure if it is related to the update or not.
https://www.nexusmods.com/witcher3/mods/7591?tab=posts

**Comment by Drakehinst** [comment]
Thanks for the heads-up!

At least this user did not seem to have a problem at launch, so this is a first confirmation that the patch works as intended.

**Pull request merged**
